
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: home_server
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clouduser -d home_server"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Default Vite dev server port
    volumes:
      - ./frontend:/app  # Mount local frontend directory
      - /app/node_modules  # Prevent overwriting node_modules
    command: npm run dev -- --host 0.0.0.0 

  api:
    build: .
    depends_on:
      frontend:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
      - ./app:/app/app  # Mount local app directory to container
      - frontend_build:/app/frontend/
    ports:
      - "8888:8888"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload
    restart: on-failure

volumes:
  postgres_data:
  frontend_build:
